### ISSUE TITLE
Escaping of '=', ']', etc. in key and value names

### ISSUE THREAD

**Issue by rjw62** [iandees/xapi-servlet#11] opened 2011-05-12 14:47 UTC
On the XAPI page on the OSM wiki it says that a set of special characters need to be escaped with a backslash if entered as part of a key or value name.

However, in the JXAPI, this escaping doesn't seem to work -- the presence of a backslash in the key and value string seems to always restult in an HTTP 400 error being returned.

For example, if I want to search for objects with the name "=", the wiki suggests I need to use: http://jxapi.openstreetmap.org/xapi/api/0.6/*[name=\=] but this just returns a 400 "Bad Request" response and a blank page.

In the case of  "=" trying to include an un-escaped "=" in the value doesn't work either. The system then produces an HTTP Status 500 error with an explanation that it either can't find a string or encounter an "=" when it was expecting "]".

Is it possible to search for tag values that contain "=" or other special characters, and if so how? If not can this functionality be added, ideally with the same escaping mechanism as the regular XAPI for compatibility reasons.

**Comment by iandees** [comment] 2012-03-10 22:12
It appears that this works as intended based on my local tests and the JUnits we have. I'm going to close it now and if you still see it in the more recent versions of jxapi please reopen the bug or file a new one.

**Closed as completed by iandees** 2012-03-10 22:12 UTC
