### ISSUE TITLE
my bbox request doesnt work anymore, but worked 14 days ago

### ISSUE THREAD

**Issue by Tilo81** [iandees/xapi-servlet#9] opened 2011-04-28 13:44 UTC
Hi, 
Sorry I posted this on your osm-Blog. I'll post further Issues here.

on apr,14 this request: *[bbox=8.173,49.815,9.173,50.554] worked fine.
size 523 MB
as well as on mar,22
size 504 MB

Yesterday in the afternoon and today (at night) I always got an error with this request. I tried 5 times each. Neither the bbox limitation of 10 sqare degrees (less than 2 sqdeg in this request) nor the syntax should be a problem in this request. What are the other limitations which might cause the request to be denied?

Have new limitations been implemented between apr,14 and apr,28? Is there a maximum for elements and might it be possible, that within the last 14 days due to adding of new elements the elements of this request have reached the maximum so the request got denied? 

Before the error occured most of the time the database query took a little less than an hour but once it took over 2 hrs and sometimes less than half an hour.

The download yesterday and today was just a final test. But with a shocking result. I hope this request will work again in the middle of May, because I plan to do some statistics on this bbox and kind of depend on it in other ways as well.

Thanks in advance, 
Tilo

**Comment by iandees** [comment] 2011-04-28 13:49
I'm looking at this now, but a couple things:
- For bounding box requests, it is preferable to use a request like "http://example.com/xapi/api/0.6/map?bbox=8.173,49.815,9.173,50.554", not api/0.6/*[bbox=...]
- What application are you using to fetch this data? wget has a default timeout of 15 minutes.
- Continuously retrying requests after the first one failed keeps the server server busy and makes others' requests slow: don't keep retrying.

**Comment by Tilo81** [comment] 2011-04-28 14:38
Thanks for the quick reply,

I call wget via a python script. I didnt know that it times out after 900sec but I just read the wget manual and added "-T 0" to deactivate the timeout. Thanks a lot. I didn't realize that it could be a wget timout problem, because the runtime shown on the stats page showed different times for each try. I just saw, that the runtime of the query keeps running even the error was thrown.

Using the old xapi was quite frustrating because the download didn't start most of the time because the connection to the xapi somehow crashed. Thats why I put the download in a loop to have a chance to get the download done. 
Working whith your jxapi was a very relyable, so I reduced the number of retries to 5. Would it be ok with you if I retry twice?

**Comment by iandees** [comment] 2011-04-28 14:44
Retrying is discouraged because you will _always_ receive a response from jxapi, it's just that it will take a long time. As you noticed, any request made to the service will force the database queries to run to completion and won't stop until it attempts to write to the client (which will fail because the TCP connection will have been closed). The more you retry, the more simultaneous database work is happening and the slower your data will come back.

**Comment by Tilo81** [comment] 2011-04-28 14:53
To your first point:
Why is this preferable to use this form. Faster? not as much work for the server? Is it possible to download larger bboxes with this request?

**Comment by iandees** [comment] 2011-04-28 14:54
I _think_ it's easier on the server. It may boil down to be the same set of
requests, but the map call is more bug-tested than the \* request.

**Comment by Tilo81** [comment] 2011-04-28 15:06
this request:
http://example.com/xapi/api/0.6/map?bbox=8.3786,50.0342,8.3975,50.0452
neither works via wget (I get some html-code) of nor via Browser (I am redirected to http://www.iana.org/domains/example/)

**Comment by iandees** [comment] 2011-04-28 15:14
Yes, because it's an example...

**Comment by iandees** [comment] 2011-04-28 15:37
I just made your request and although it took 40 minutes it worked just fine. Be patient and you will eventually get your data back.

I'm going to close this issue for now as I can't reproduce any client-side errors. The "ERROR" you see on the stats list simply means that your client closed the connection before or during the serialization phase.

**Closed as completed by iandees** 2011-04-28 15:37 UTC

**Comment by Tilo81** [comment] 2011-05-03 13:19
Hi Ian,
setting the wget timeout to 5 hrs (-T 18000) worked fine. Now wget waits 5 hrs for an answer from jxapi. Unfortunately, it still only works with small bboxes. With the request above (both, *[bbox=8.173,49.815,9.173,50.554] and map?bbox=8.173,49.815,9.173,50.554) the query ends and serialization starts while wget is waiting (small bboxes get 200 in this phase and the download starts). With this bbox nothing changes in the wget window (still waiting for an answer...). After a few minutes the status on the stats page changes to ERROR and wget waits until the 5 hours are over.
It seems that somehow the connection between wget and jxapi gets killed after a while of waiting for the reaction of jxapi, but there are nothing changing in the wget window.

Do you have an idea what might cause this behaviour? It worked when you sent the request, so there must be something wrong with my wget call or my computersettings. I use Windows7. 

How did you successfully download the request? 

My wget call (Python) is: 
url="http://jxapi.openstreetmap.org/xapi/api/0.6/*[bbox=8.173,49.815,9.173,50.554]"
or
url="http://jxapi.openstreetmap.org/xapi/api/0.6/map?bbox=8.173,49.815,9.173,50.554"

subprocess.call(["wget", "-T 18000", "-O", r"C:\test.osm", url])

or via command line:
wget -T 18000 -O C:\testfolder\data.osm http://jxapi.openstreetmap.org/xapi/api/0.6/map?bbox=8.173,49.815,9.173,50.554

All produce the same result: Error after about an hour (or more if the server is busy), 450 elements???, Serialization fails. no reaction in wget window. waits 5 hours.

Interpreting the bbox request errors on the stats page it seems, that some other users might have similar problems. correct bbox but error (and often retries which slow down the jxapi).

By the way, I reduced retrying to one retry ;)

Thanks, Tilo

**Comment by Tilo81** [comment] 2011-05-03 13:23
the commandline call contains backslashes in the save destination, which aren't shown here. 
Test: C:\testfolder\data.osm

**Comment by Tilo81** [comment] 2011-05-09 15:41
this night when there were no other queries running the request worked. the query took only about 11 mins and the download worked fine.
Today, I get the error again. Here the error description (thanks for implementing!):

```
ERROR
```

org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to write data.
    at org.openstreetmap.osmosis.xml.common.ElementWriter.addAttribute(ElementWriter.java:214)
    at org.openstreetmap.osmosis.xml.v0_6.impl.NodeWriter.process(NodeWriter.java:74)
    at org.openstreetmap.osmosis.xml.v0_6.impl.OsmWriter$SubElementWriter.process(OsmWriter.java:147)
    at org.openstreetmap.osmosis.core.container.v0_6.NodeContainer.process(NodeContainer.java:58)
    at org.openstreetmap.osmosis.xml.v0_6.impl.OsmWriter.process(OsmWriter.java:82)
    at org.openstreetmap.osmosis.xml.v0_6.XmlWriter.process(XmlWriter.java:58)
    at com.yellowbkpk.geo.xapi.servlet.XapiServlet.doGet(XapiServlet.java:139)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:662)
Caused by: ClientAbortException:  java.net.SocketException: Connection timed out
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:358)
    at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:325)
    at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:381)
    at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:370)
    at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:89)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:202)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:263)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:106)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:190)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:111)
    at java.io.BufferedWriter.write(BufferedWriter.java:212)
    at java.io.Writer.write(Writer.java:140)
    at java.io.Writer.append(Writer.java:210)
    at org.openstreetmap.osmosis.xml.common.ElementWriter.addAttribute(ElementWriter.java:209)
    ... 20 more
Caused by: java.net.SocketException: Connection timed out
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
    at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:741)
    at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:434)
    at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:349)
    at org.apache.coyote.http11.InternalOutputBuffer$OutputStreamOutputBuffer.doWrite(InternalOutputBuffer.java:765)
    at org.apache.coyote.http11.filters.IdentityOutputFilter.doWrite(IdentityOutputFilter.java:127)
    at org.apache.coyote.http11.InternalOutputBuffer.doWrite(InternalOutputBuffer.java:574)
    at org.apache.coyote.Response.doWrite(Response.java:560)
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353)
    ... 33 more

as expected, it seems that the connection timed out. But why? wget didn't. it would time out after 5 hrs (-T 18000). 

I just tried again. Serialization started after 17 mins and the error occured. I think, if the database query takes longer than 15 min, somehow the connection gets lost. Might this still be an wget issue even if the timeout is disabled or a computer issue or a server issue?

Thanks 
Tilo

**Comment by iandees** [comment] 2011-05-09 15:43
I imagine it's your conenction or the OS.

Can you try the same query on a different OS? I've tried it on Linux from
two different connections here in the US. If it works on the same connection
under a different OS then your OS is to blame. Next you could try same OS
with a different network connection.

**Comment by Tilo81** [comment] 2011-05-09 23:42
I'll try it on winXP tomorrow and if this doesn't work I'll try Linux (Knoppix). I have used Knoppix just to recover data from broken Windows machines until now, but It's damn time to get to know Linux ;)

did you use wget as well?

**Comment by iandees** [comment] 2011-05-09 23:49
Yep, I used wget with a timeout of "0" (zero) to disable it.

**Comment by Tilo81** [comment] 2011-05-10 10:53
I recall, the request took you 40 mins. The request, which worked with my machine the night two days ago took me 41 mins. The time for the database query was only 11 mins in this case and 30 mins serialization, which is the reason it worked. So probably the database query in your try also took less than 15 min. Did you try a large bbox which definately need a longer database query than 15 min yet? Like bbox=8,49,10,51 or a request thats just a litte smaller than the allowed 10 square degrees like bbox=7,49,12,50.999 ? If this works on your machine the problem is definately my OS or my connection. 
Windows beeing the Problem would be really bad, because the program I am writing is going to be used by Windows users.

**Comment by Tilo81** [comment] 2011-05-19 12:10
After some testing on other machines and other Windows OSs with different internet connections I am quite frustrated, because I always run into the same error, when the database query itself exceeds about 15 min. 
It doesn't make sense for me to test on Linux, because my programm will only be used on Windows machines. 

Might the reason be, that I use the url ...openstreetmap.org... instead of ...openstreetmap.us... (using .us leads to a dnserror)?

I am now working on a workaround with splitting up the bboxes into 1 sqdeg requests, but it would be really nice if we could still get the connection problem solved.

Thanks
